# Generated by Django 2.2.3 on 2020-06-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200620_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_time'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
